name: Build KianaBH3 Multi Platform

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:

  build:

    strategy:
      matrix:

        include:

          # Android Termux
          - rid: linux-arm64
            name: Android-Termux-arm64

          # Linux服务器
          - rid: linux-x64
            name: Linux-x64

          # Windows电脑
          - rid: win-x64
            name: Windows-x64


    runs-on: ubuntu-24.04


    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive


    - name: Setup dotnet 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x


    - name: Install tools
      run:

        sudo apt update

        sudo apt install -y protobuf-compiler


    - name: Restore
      run:

        dotnet restore


    - name: Publish

      run: |

        dotnet publish \
        KianaBH/KianaBH.csproj \
        -c Release \
        -r ${{matrix.rid}} \
        --self-contained false \
        -o build/${{matrix.name}}



    - name: Upload

      uses: actions/upload-artifact@v4

      with:

        name: KianaBH3-${{matrix.name}}

        path: build/${{matrix.name}}
